language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
  yarn: true
before_script:
  - yarn start --silent &
script:
  - yarn cypress:run 
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local-dir: build
#   on:
#     branch: master
addons:
  artifacts: 
    paths:
      - ./cypress/screenshots
    s3_region: "eu-central-1"