language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
  yarn: true
script:
  - yarn build
  - yarn coverage
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: master